pip install transformers
pip install datasets
pip install zstandard
pip install deepspeed
pip install accelerate
pip install mpi4py
pip install scikit-learn 
pip install matplotlib 
pip install plotly 
pip install torch
