from transformers import AutoModelForCausalLM
from ..utils.attack_utils import *
from ..utils.dataset_utils import *
# from ..utils.detect_gpt_utils import *
# from ..utils.plot_utils import *

class MIA:
    def __init__(self, model_path, model_revision=None, cache_dir=None):
        """
        Base class for all membership inference attacks. Contains a "base" model image. 
            model_path: path to the model to be attacked
            model_revision: revision of the model to be attacked
            cache_dir: directory to cache the model
        """
        self.model_path      = model_path
        self.model_name      = self.model_path.split("/")[-1]
        self.model_revision  = model_revision
        self.cache_dir       = cache_dir
    
    def get_model(self):
        """
        Returns the model that this MIA uses.
        """
        return AutoModelForCausalLM.from_pretrained(self.model_path, revision=self.model_revision, cache_dir=self.cache_dir)
    
    def get_statistics(self):
        """
        Abstract method to get the statistics used for ROC plotting.

        This method should be implemented by subclasses to return the training and validation
        statistics necessary for plotting the ROC curve.
        """
        raise NotImplementedError()

    def get_default_title(self):
        """
        Abstract method to provide a default title for attack plots.

        This method should be implemented by subclasses to provide a meaningful default 
        title that describes the specific attack being performed.

        Raises:
            NotImplementedError: If the method is not overridden in the subclass.
        """
        raise NotImplementedError()

    def attack_plot_ROC(self, title=None, log_scale=False, show_plot=False, save_name=None):
        """
        Generates and displays or saves a plot of the ROC curve for the membership inference attack.

        This method uses the statistics returned by `get_statistics` to create a ROC curve that 
        illustrates the performance of the attack. The plot can be displayed in a log scale, 
        shown directly, or saved to a file.

        Args:
            title (str, optional): The title for the ROC plot. If not specified, `get_default_title` 
                is called to generate a default title. Defaults to None.
            log_scale (bool, optional): Whether to plot the ROC curve on a logarithmic scale. 
                Defaults to False.
            show_plot (bool, optional): Whether to display the plot. If False, the plot is not 
                shown but is saved directly to the file specified by `save_name`. Defaults to True.
            save_name (str, optional): The file name or path to save the plot image. If not 
                specified, the default name is generated by `get_default_title` with an 
                appropriate file extension. Defaults to None.
        """
        train_statistics, val_statistics = self.get_statistics()
        if title is None:
            title = self.get_default_title()
        if save_name is None:
            save_name = self.get_default_title() + (" log.png" if log_scale else ".png")
        plot_ROC(train_statistics, val_statistics, title, log_scale=log_scale, show_plot=show_plot, save_name=save_name)